export const ADD_COMMENT = 'ADD_COMMENT'
export const DEL_COMMENT = 'DEL_COMMENT'
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS'

export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'